name: Build and Deploy to prod

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build:player

      - name: Add dist folder to git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add dist -f
          git commit -m "Update prod."
          git push

