name: Build and Deploy to prod

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Download Firefox
        uses: browser-actions/setup-firefox@latest

      - name: Add FIREFOX_BIN for Karma
        run: echo "FIREFOX_BIN=$(which firefox)" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
